--Proyecto Final - Administracion Base de Daton
--GRUPO 4



/****************************************************************************************************************************************************************
***                                                                        TABLESPACE                                                                         ***
****************************************************************************************************************************************************************/


--Creacion del Tablespace
CREATE TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS
DATAFILE 'C:\ORACLE\ORADATA\ORCL\fide_ropasclaras_final_tbs.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 50M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
/
/****************************************************************************************************************************************************************
***                                                                    USUARIOS Y PERFILES                                                                      ***
****************************************************************************************************************************************************************/

--Creacion de usuario
CREATE USER FIDE_ROPASCLARAS_FINAL IDENTIFIED BY 12345
DEFAULT TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS
QUOTA UNLIMITED ON FIDE_ROPASCLARAS_FINAL_TBS;

GRANT CREATE SESSION TO FIDE_ROPASCLARAS_FINAL;
GRANT DBA TO FIDE_ROPASCLARAS_FINAL;
/
CREATE PROFILE FIDE_ROPASCLARAS_PROF LIMIT
SESSIONS_PER_USER 10
CPU_PER_SESSION UNLIMITED
PASSWORD_LIFE_TIME 90;

ALTER USER FIDE_ROPASCLARAS_FINAL PROFILE FIDE_ROPASCLARAS_PROF;
/
AUDIT ALL BY FIDE_ROPASCLARAS_FINAL BY ACCESS;


/****************************************************************************************************************************************************************
***                                                                          TABLAS                                                                           ***
****************************************************************************************************************************************************************/
-- 1. Tabla ESTADO 
CREATE TABLE FIDE_ESTADO_TB (
    ID_Estado NUMBER CONSTRAINT FIDE_ESTADO_TB_ID_Estado_PK PRIMARY KEY,
    Nombre_estado VARCHAR2(100),
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 2. Tabla PAIS 
CREATE TABLE FIDE_PAIS_TB (
    ID_Pais NUMBER CONSTRAINT FIDE_PAIS_TB_ID_Pais_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 3. Tabla PROVINCIA 
CREATE TABLE FIDE_PROVINCIA_TB (
    ID_Provincia NUMBER CONSTRAINT FIDE_PROVINCIA_TB_ID_Provincia_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 4. Tabla CANTON 
CREATE TABLE FIDE_CANTON_TB (
    ID_Canton NUMBER CONSTRAINT FIDE_CANTON_TB_ID_Canton_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 5. Tabla DISTRITO 
CREATE TABLE FIDE_DISTRITO_TB (
    ID_Distrito NUMBER CONSTRAINT FIDE_DISTRITO_TB_ID_Distrito_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 6. Tabla CLIENTES 
CREATE TABLE FIDE_CLIENTES_TB (
    ID_Cliente NUMBER CONSTRAINT FIDE_CLIENTES_TB_ID_Cliente_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    Telefono VARCHAR2(15),
    Cedula NUMBER CONSTRAINT FIDE_CLIENTES_TB_Cedula_UQ UNIQUE,
    Correo VARCHAR2(50) CONSTRAINT FIDE_CLIENTES_TB_Correo_UQ UNIQUE,
    Pais NUMBER, 
    Provincia NUMBER,
    Canton NUMBER,
    Distrito NUMBER,
    Foto BLOB,
    Estado_ID NUMBER,
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR2(100)
)  TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 7. Tabla PROVEEDORES 
CREATE TABLE FIDE_PROVEEDORES_TB (
    ID_Proveedor NUMBER CONSTRAINT FIDE_PROVEEDORES_TB_ID_Proveedor_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    Detalles VARCHAR2(250),
    Estado_ID NUMBER,
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 8. Tabla INVENTARIO 
CREATE TABLE FIDE_INVENTARIO_TB (
    ID_Producto NUMBER CONSTRAINT FIDE_INVENTARIO_TB_ID_Producto_PK PRIMARY KEY,
    Nombre VARCHAR2(100),
    Imagen BLOB,
    Precio NUMBER,
    Detalle VARCHAR2(250),
    Cantidad NUMBER,
    Categoria VARCHAR2(50),
    Proveedor_ID NUMBER,
    Estado_ID NUMBER, 
    Fecha_Entrada DATE,
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 9. Tabla FEEDBACK
CREATE TABLE FIDE_FEEDBACK_TB (
    ID_Feedback NUMBER CONSTRAINT FIDE_FEEDBACK_TB_ID_Feedback_PK PRIMARY KEY,
    Cliente_ID NUMBER,
    Producto_ID NUMBER,
    Comentario VARCHAR2(500),
    Estado_ID NUMBER, 
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;
 
-- 10. Tabla CARRITO 
CREATE TABLE FIDE_CARRITO_TB (
    ID_Carrito NUMBER CONSTRAINT FIDE_CARRITO_TB_ID_Carrito_PK PRIMARY KEY,
    Producto_ID NUMBER, 
    Cantidad NUMBER,
    Subtotal NUMBER,
    Estado_ID NUMBER,  
    Cliente_ID NUMBER,
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 11. Tabla CARRITO TEMP
CREATE TABLE FIDE_CARRITO_TEMP_TB (
    ID_Carrito_Temp NUMBER CONSTRAINT FIDE_CARRITO_TB_ID_Carrito_Temp_PK PRIMARY KEY,
    Producto_ID NUMBER, 
    Cantidad NUMBER,
    Subtotal NUMBER,
    Estado_ID NUMBER,  
    Cliente_ID NUMBER,
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 12. Tabla METODO_PAGO 
CREATE TABLE FIDE_METODO_PAGO_TB (
    ID_Metodo NUMBER CONSTRAINT FIDE_METODO_PAGO_TB_ID_Metodo_PK PRIMARY KEY,
    Descripcion VARCHAR2(100),
    Estado_ID NUMBER,
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 13. Tabla FACTURA 
CREATE TABLE FIDE_FACTURA_TB (
    ID_Factura NUMBER CONSTRAINT FIDE_FACTURA_TB_ID_Factura_PK PRIMARY KEY,
    Cliente_ID NUMBER, 
    Metodo_ID NUMBER, 
    Detalle VARCHAR2(500),
    TotalDeLineas NUMBER,
    Total NUMBER,
    Subtotal NUMBER,
    IVA NUMBER,
    Costo_Envio NUMBER,
    Estado_ID NUMBER,  
    Carrito_ID NUMBER,
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 14. Tabla ENVIOS 
CREATE TABLE FIDE_ENVIOS_TB (
    ID_Envios NUMBER CONSTRAINT FIDE_ENVIOS_TB_ID_Envios_PK PRIMARY KEY,
    Cliente_ID NUMBER, 
    Producto_ID NUMBER,
    Empresa_ID NUMBER, 
    Estado_ID NUMBER,  
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;

-- 15. Tabla EMPRESA ENVIOS 
CREATE TABLE FIDE_EMPRESA_ENVIOS_TB (
    ID_Mensajero NUMBER CONSTRAINT FIDE_EMPRESA_ENVIOS_TB_ID_Mensajero_PK PRIMARY KEY,
    Empresa VARCHAR2(100),
    Precio NUMBER,
    Estado_ID NUMBER CONSTRAINT FIDE_EMPRESA_ENVIOS_TB_Estado_ID_FK REFERENCES FIDE_ESTADO_TB(ID_Estado),
    CREADO_POR VARCHAR(100),
    FECHA_CREACION TIMESTAMP,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION TIMESTAMP,
    ESTADO VARCHAR2(10),
    ACCION VARCHAR(100)
) TABLESPACE FIDE_ROPASCLARAS_FINAL_TBS;



/****************************************************************************************************************************************************************
***                                                                          ALTERS FK                                                                        ***
****************************************************************************************************************************************************************/
-- Agregar FK a FIDE_CLIENTES_TB
ALTER TABLE FIDE_CLIENTES_TB ADD CONSTRAINT FIDE_CLIENTES_TB_Pais_FK FOREIGN KEY (Pais) REFERENCES FIDE_PAIS_TB(ID_Pais);
ALTER TABLE FIDE_CLIENTES_TB ADD CONSTRAINT FIDE_CLIENTES_TB_Provincia_FK FOREIGN KEY (Provincia) REFERENCES FIDE_PROVINCIA_TB(ID_Provincia);
ALTER TABLE FIDE_CLIENTES_TB ADD CONSTRAINT FIDE_CLIENTES_TB_Canton_FK FOREIGN KEY (Canton) REFERENCES FIDE_CANTON_TB(ID_Canton);
ALTER TABLE FIDE_CLIENTES_TB ADD CONSTRAINT FIDE_CLIENTES_TB_Distrito_FK FOREIGN KEY (Distrito) REFERENCES FIDE_DISTRITO_TB(ID_Distrito);
ALTER TABLE FIDE_CLIENTES_TB ADD CONSTRAINT FIDE_CLIENTES_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

-- Agregar FK a FIDE_PROVEEDORES_TB
ALTER TABLE FIDE_PROVEEDORES_TB ADD CONSTRAINT FIDE_PROVEEDORES_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

-- Agregar FK a FIDE_INVENTARIO_TB
ALTER TABLE FIDE_INVENTARIO_TB ADD CONSTRAINT FIDE_INVENTARIO_TB_Proveedor_ID_FK FOREIGN KEY (Proveedor_ID) REFERENCES FIDE_PROVEEDORES_TB(ID_Proveedor);
ALTER TABLE FIDE_INVENTARIO_TB ADD CONSTRAINT FIDE_INVENTARIO_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

-- Agregar FK a FIDE_FEEDBACK_TB
ALTER TABLE FIDE_FEEDBACK_TB ADD CONSTRAINT FIDE_FEEDBACK_TB_Cliente_ID_FK FOREIGN KEY (Cliente_ID) REFERENCES FIDE_CLIENTES_TB(ID_Cliente);
ALTER TABLE FIDE_FEEDBACK_TB ADD CONSTRAINT FIDE_FEEDBACK_TB_Producto_ID_FK FOREIGN KEY (Producto_ID) REFERENCES FIDE_INVENTARIO_TB(ID_Producto);
ALTER TABLE FIDE_FEEDBACK_TB ADD CONSTRAINT FIDE_FEEDBACK_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

-- Agregar FK a FIDE_CARRITO_TB
ALTER TABLE FIDE_CARRITO_TB ADD CONSTRAINT FIDE_CARRITO_TB_Producto_ID_FK FOREIGN KEY (Producto_ID) REFERENCES FIDE_INVENTARIO_TB(ID_Producto);
ALTER TABLE FIDE_CARRITO_TB ADD CONSTRAINT FIDE_CARRITO_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);
ALTER TABLE FIDE_CARRITO_TB ADD CONSTRAINT FIDE_CARRITO_TB_Cliente_ID_FK FOREIGN KEY (Cliente_ID) REFERENCES FIDE_CLIENTES_TB(ID_Cliente);

--Agregar FK a FIDE_CARRITO_TEMP_TB
ALTER TABLE FIDE_CARRITO_TEMP_TB ADD CONSTRAINT FIDE_CARRITO_TEMP_TB_Producto_ID_FK FOREIGN KEY (Producto_ID) REFERENCES FIDE_INVENTARIO_TB(ID_Producto);
ALTER TABLE FIDE_CARRITO_TEMP_TB ADD CONSTRAINT FIDE_CARRITO_TEMP_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);
ALTER TABLE FIDE_CARRITO_TEMP_TB ADD CONSTRAINT FIDE_CARRITO_TEMP_TB_Cliente_ID_FK FOREIGN KEY (Cliente_ID) REFERENCES FIDE_CLIENTES_TB(ID_Cliente);

-- Agregar FK a FIDE_METODO_PAGO_TB
ALTER TABLE FIDE_METODO_PAGO_TB ADD CONSTRAINT FIDE_METODO_PAGO_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

-- Agregar FK a FIDE_FACTURA_TB
ALTER TABLE FIDE_FACTURA_TB ADD CONSTRAINT FIDE_FACTURA_TB_Cliente_ID_FK FOREIGN KEY (Cliente_ID) REFERENCES FIDE_CLIENTES_TB(ID_Cliente);
ALTER TABLE FIDE_FACTURA_TB ADD CONSTRAINT FIDE_FACTURA_TB_Metodo_ID_FK FOREIGN KEY (Metodo_ID) REFERENCES FIDE_METODO_PAGO_TB(ID_Metodo);
ALTER TABLE FIDE_FACTURA_TB ADD CONSTRAINT FIDE_FACTURA_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

-- Agregar FK a FIDE_ENVIOS_TB
ALTER TABLE FIDE_ENVIOS_TB ADD CONSTRAINT FIDE_ENVIOS_TB_Cliente_ID_FK FOREIGN KEY (Cliente_ID) REFERENCES FIDE_CLIENTES_TB(ID_Cliente);
ALTER TABLE FIDE_ENVIOS_TB ADD CONSTRAINT FIDE_ENVIOS_TB_Producto_ID_FK FOREIGN KEY (Producto_ID) REFERENCES FIDE_INVENTARIO_TB(ID_Producto);
ALTER TABLE FIDE_ENVIOS_TB ADD CONSTRAINT FIDE_ENVIOS_TB_Empresa_ID_FK FOREIGN KEY (Empresa_ID) REFERENCES FIDE_EMPRESA_ENVIOS_TB(ID_Mensajero);
ALTER TABLE FIDE_ENVIOS_TB ADD CONSTRAINT FIDE_ENVIOS_TB_Estado_ID_FK FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADO_TB(ID_Estado);

/****************************************************************************************************************************************************************
***                                                                    TRIGGERS Y SECUENCIAS                                                                  ***
****************************************************************************************************************************************************************/
-- 1. Tabla FIDE_ESTADO_TB
CREATE SEQUENCE ID_ESTADO_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Estado IS NULL THEN
            SELECT ID_ESTADO_SEQ.NEXTVAL INTO :NEW.ID_Estado FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 2. Tabla FIDE_PAIS_TB
CREATE SEQUENCE ID_PAIS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Pais IS NULL THEN
            SELECT ID_PAIS_SEQ.NEXTVAL INTO :NEW.ID_Pais FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 3. Tabla FIDE_PROVINCIA_TB
CREATE SEQUENCE ID_PROVINCIA_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Provincia IS NULL THEN
            SELECT ID_PROVINCIA_SEQ.NEXTVAL INTO :NEW.ID_Provincia FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 4. Tabla FIDE_CANTON_TB
CREATE SEQUENCE ID_CANTON_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Canton IS NULL THEN
            SELECT ID_CANTON_SEQ.NEXTVAL INTO :NEW.ID_Canton FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 5. Tabla FIDE_DISTRITO_TB
CREATE SEQUENCE ID_DISTRITO_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Distrito IS NULL THEN
            SELECT ID_DISTRITO_SEQ.NEXTVAL INTO :NEW.ID_Distrito FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 6. Tabla FIDE_CLIENTES_TB
CREATE SEQUENCE ID_CLIENTES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLIENTES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Cliente IS NULL THEN
            SELECT ID_CLIENTES_SEQ.NEXTVAL INTO :NEW.ID_Cliente FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 7. Tabla FIDE_PROVEEDORES_TB
CREATE SEQUENCE ID_PROVEEDORES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Proveedor IS NULL THEN
            SELECT ID_PROVEEDORES_SEQ.NEXTVAL INTO :NEW.ID_Proveedor FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 8. Tabla FIDE_INVENTARIO_TB
CREATE SEQUENCE ID_INVENTARIO_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Producto IS NULL THEN
            SELECT ID_INVENTARIO_SEQ.NEXTVAL INTO :NEW.ID_Producto FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 9. Tabla FIDE_FEEDBACK_TB
CREATE SEQUENCE ID_FEEDBACK_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_FEEDBACK_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_FEEDBACK_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Feedback IS NULL THEN
            SELECT ID_FEEDBACK_SEQ.NEXTVAL INTO :NEW.ID_Feedback FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 10. Tabla FIDE_CARRITO_TB
CREATE SEQUENCE ID_CARRITO_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CARRITO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Carrito IS NULL THEN
            SELECT ID_CARRITO_SEQ.NEXTVAL INTO :NEW.ID_Carrito FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 11. Tabla FIDE_CARRITO_TEMP_TB
CREATE SEQUENCE ID_CARRITO_TEMP_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CARRITO_TEMP_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_CARRITO_TEMP_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Carrito_Temp IS NULL THEN
            SELECT ID_CARRITO_TEMP_SEQ.NEXTVAL INTO :NEW.ID_Carrito_Temp FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 12. Tabla FIDE_METODO_PAGO_TB
CREATE SEQUENCE ID_METODO_PAGO_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Metodo IS NULL THEN
            SELECT ID_METODO_PAGO_SEQ.NEXTVAL INTO :NEW.ID_Metodo FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 13. Tabla FIDE_FACTURA_TB
CREATE SEQUENCE ID_FACTURA_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_FACTURA_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Factura IS NULL THEN
            SELECT ID_FACTURA_SEQ.NEXTVAL INTO :NEW.ID_Factura FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 14. Tabla FIDE_ENVIOS_TB
CREATE SEQUENCE ID_ENVIOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ENVIOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_ENVIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Envios IS NULL THEN
            SELECT ID_ENVIOS_SEQ.NEXTVAL INTO :NEW.ID_Envios FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

-- 15. Tabla FIDE_EMPRESA_ENVIOS_TB
CREATE SEQUENCE ID_EMPRESA_ENVIOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_EMPRESA_ENVIOS_TB_TRG
BEFORE INSERT OR UPDATE ON FIDE_EMPRESA_ENVIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_Mensajero IS NULL THEN
            SELECT ID_EMPRESA_ENVIOS_SEQ.NEXTVAL INTO :NEW.ID_Mensajero FROM DUAL;
        END IF;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION := 'INSERT';
        :NEW.ESTADO := 'A';
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

/****************************************************************************************************************************************************************
***                                                                    Procedimiento Almacenados                                                              ***
****************************************************************************************************************************************************************/
--1. Procedimiento para FIDE_ESTADO_TB
CREATE OR REPLACE PROCEDURE FIDE_ESTADO_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_ESTADO_TB (NOMBRE_ESTADO)
    VALUES (V_Nombre);
    COMMIT;
END FIDE_ESTADO_TB_INSERTAR_SP;
/

--2. Procedimiento para FIDE_PAIS_TB
CREATE OR REPLACE PROCEDURE FIDE_PAIS_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_PAIS_TB (Nombre)
    VALUES (V_Nombre);
    COMMIT;
END FIDE_PAIS_TB_INSERTAR_SP;
/

--3. Procedimiento para FIDE_PROVINCIA_TB
CREATE OR REPLACE PROCEDURE FIDE_PROVINCIA_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_PROVINCIA_TB (Nombre)
    VALUES (V_Nombre);
    COMMIT;
END FIDE_PROVINCIA_TB_INSERTAR_SP;
/

--4. Procedimiento para FIDE_CANTON_TB
CREATE OR REPLACE PROCEDURE FIDE_CANTON_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_CANTON_TB (Nombre)
    VALUES (V_Nombre);
    COMMIT;
END FIDE_CANTON_TB_INSERTAR_SP;
/

--5. Procedimiento para FIDE_DISTRITO_TB
CREATE OR REPLACE PROCEDURE FIDE_DISTRITO_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_DISTRITO_TB (Nombre)
    VALUES (V_Nombre);
    COMMIT;
END FIDE_DISTRITO_TB_INSERTAR_SP;
/

-- 6. Procedimiento para FIDE_CLIENTES_TB
CREATE OR REPLACE PROCEDURE FIDE_CLIENTES_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2,
    V_Telefono IN VARCHAR2,
    V_Cedula IN NUMBER,
    V_Correo IN VARCHAR2,
    V_Pais IN NUMBER,
    V_Provincia IN NUMBER,
    V_Canton IN NUMBER,
    V_Distrito IN NUMBER,
    V_Foto IN BLOB,
    V_Estado_ID IN NUMBER
) 
AS 
BEGIN
    INSERT INTO FIDE_CLIENTES_TB (
        Nombre, Telefono, Cedula, Correo, 
        Pais, Provincia, Canton, Distrito, Foto, 
        Estado_ID
    ) VALUES (
        V_Nombre, 
        V_Telefono, 
        V_Cedula, 
        V_Correo, 
        V_Pais, 
        V_Provincia, 
        V_Canton, 
        V_Distrito, 
        V_Foto, 
        V_Estado_ID 
    );
    COMMIT;
END FIDE_CLIENTES_TB_INSERTAR_SP;
/

-- 7. Procedimiento para FIDE_PROVEEDORES_TB
CREATE OR REPLACE PROCEDURE FIDE_PROVEEDORES_TB_INSERTAR_SP (
    V_Nombre IN VARCHAR2,
    V_Detalles IN VARCHAR2,
    V_Estado_ID NUMBER
) IS
BEGIN
    INSERT INTO FIDE_PROVEEDORES_TB (Nombre, Detalles, Estado_ID)
    VALUES ( V_Nombre, V_Detalles , V_Estado_ID);
    COMMIT;
END FIDE_PROVEEDORES_TB_INSERTAR_SP;
/

-- 8. Procedimiento para FIDE_INVENTARIO_TB
CREATE OR REPLACE PROCEDURE FIDE_INVENTARIO_TB_INSERTAR_SP ( 
    V_Nombre IN VARCHAR2,
    V_Imagen IN BLOB,
    V_Precio IN NUMBER,
    V_Detalle IN VARCHAR2,
    V_Cantidad IN NUMBER,
    V_Categoria IN VARCHAR2,
    V_Proveedor_ID IN NUMBER,
    V_Estado_ID IN NUMBER
) IS
BEGIN
    INSERT INTO FIDE_INVENTARIO_TB (Nombre, Imagen, Precio, Detalle, Cantidad, Categoria, Proveedor_ID, ESTADO_ID)
    VALUES (V_Nombre, V_Imagen, V_Precio, V_Detalle, V_Cantidad, V_Categoria, V_Proveedor_ID, V_Estado_ID);
    COMMIT;
END FIDE_INVENTARIO_TB_INSERTAR_SP;

/

--9. Procedimineto para FIDE_FEEDBACK_TB
CREATE OR REPLACE PROCEDURE FIDE_FEEDBACK_TB_INSERTAR_SP (
    V_Cliente_ID IN NUMBER,
    V_Producto_ID IN NUMBER,
    V_Comentario IN VARCHAR2,
    V_Estado_ID IN NUMBER
) 
AS
BEGIN
    INSERT INTO FIDE_FEEDBACK_TB (Cliente_ID, Producto_ID,Comentario, Estado_ID) 
    VALUES (V_Cliente_ID, V_Producto_ID, V_Comentario, V_Estado_ID);
    
    COMMIT;
END FIDE_FEEDBACK_TB_INSERTAR_SP;
/


--10.Procedimiento para FIDE_CARRITO_TB
CREATE OR REPLACE PROCEDURE FIDE_CARRITO_TB_INSERTAR_SP (
    V_Producto_ID IN NUMBER,
    V_Cantidad IN NUMBER,
    V_Subtotal IN NUMBER,
    V_Estado_ID IN NUMBER,
    V_Cliente_ID IN NUMBER
) IS
BEGIN
    INSERT INTO FIDE_CARRITO_TB (Producto_ID, Cantidad, Subtotal, Estado_ID, Cliente_ID) 
    VALUES (V_Producto_ID, V_Cantidad, V_Subtotal, V_Estado_ID, V_Cliente_ID);
    
    COMMIT;
END FIDE_CARRITO_TB_INSERTAR_SP;
/

--11. Procedimiento para FIDE_CARRITO_TEMP_TB
CREATE OR REPLACE PROCEDURE FIDE_CARRITO_TEMP_TB_INSERTAR_SP (
    V_Producto_ID IN NUMBER,
    V_Cantidad IN NUMBER,
    V_Subtotal IN NUMBER,
    V_Estado_ID IN NUMBER,
    V_Cliente_ID IN NUMBER
) IS
BEGIN
    INSERT INTO FIDE_CARRITO_TB (Producto_ID, Cantidad, Subtotal, Estado_ID, Cliente_ID)
    VALUES (V_Producto_ID, V_Cantidad, V_Subtotal, V_Estado_ID, V_Cliente_ID);
    COMMIT;
END FIDE_CARRITO_TEMP_TB_INSERTAR_SP;
/

--12.  Procedimiento para FIDE_METODO_PAGO_TB
CREATE OR REPLACE PROCEDURE FIDE_METODO_PAGO_TB_INSERTAR_SP (
    V_Descripcion IN VARCHAR2,
    V_Estado_ID IN NUMBER

) IS
BEGIN
    INSERT INTO FIDE_METODO_PAGO_TB (Descripcion, Estado_ID)
    VALUES (V_Descripcion, V_Estado_ID);
    COMMIT;
END FIDE_METODO_PAGO_TB_INSERTAR_SP;
/

--13. Procedimiento para FIDE_FACTURA_TB
CREATE OR REPLACE PROCEDURE FIDE_FACTURA_TB_INSERTAR_SP (
    V_Cliente_ID IN NUMBER, 
    V_Metodo_ID IN NUMBER, 
    V_Detalle IN VARCHAR2,
    V_TotalDeLineas IN NUMBER,
    V_Total IN NUMBER,
    V_Subtotal IN NUMBER,
    V_IVA IN NUMBER,
    V_Costo_Envio IN NUMBER,
    V_Estado_ID IN NUMBER,  
    V_Carrito_ID IN NUMBER
) IS
BEGIN
    INSERT INTO FIDE_FACTURA_TB (
        Cliente_ID, Metodo_ID, Detalle, TotalDeLineas, Total, Subtotal, IVA, Costo_Envio, Estado_ID, Carrito_ID)
    VALUES (V_Cliente_ID, V_Metodo_ID, V_Detalle, V_TotalDeLineas, V_Total, V_Subtotal, V_IVA, V_Costo_Envio, V_Estado_ID, V_Carrito_ID);
    COMMIT;
END FIDE_FACTURA_TB_INSERTAR_SP;
/

--14. Procedimiento para FIDE_ENVIOS_TB
CREATE OR REPLACE PROCEDURE FIDE_ENVIOS_TB_INSERTAR_SP (
    V_Cliente_ID IN NUMBER, 
    V_Producto_ID IN NUMBER,
    V_Empresa_ID IN NUMBER, 
    V_Estado_ID IN NUMBER  
) IS
BEGIN
    INSERT INTO FIDE_ENVIOS_TB (Cliente_ID, Producto_ID,Empresa_ID, Estado_ID)
    VALUES (V_Cliente_ID, V_Producto_ID, V_Empresa_ID, V_Estado_ID);
    COMMIT;
END FIDE_ENVIOS_TB_INSERTAR_SP;
/

--15. Procedimiento para FIDE_EMPRESA_ENVIOS_TB
CREATE OR REPLACE PROCEDURE FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP (
    V_Empresa IN VARCHAR2,
    V_Precio IN NUMBER,
    V_Estado_ID IN NUMBER
) IS
BEGIN
    INSERT INTO FIDE_EMPRESA_ENVIOS_TB (Empresa, Precio, Estado_ID)
    VALUES (V_Empresa, V_Precio, V_Estado_ID);
    COMMIT;
END FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP;
/

/****************************************************************************************************************************************************************
***                                                                       Insert                                                                              ***
****************************************************************************************************************************************************************/
-- Inserciones para la tabla FIDE_ESTADO_TB
BEGIN
    FIDE_ESTADO_TB_INSERTAR_SP('Activo');
    FIDE_ESTADO_TB_INSERTAR_SP('Inactivo');
END;
/

-- Inserciones para la tabla FIDE_PAIS_TB
BEGIN
    FIDE_PAIS_TB_INSERTAR_SP('Costa Rica');
    FIDE_PAIS_TB_INSERTAR_SP('Panamá');
    FIDE_PAIS_TB_INSERTAR_SP('Nicaragua');
    FIDE_PAIS_TB_INSERTAR_SP('El Salvador');
    FIDE_PAIS_TB_INSERTAR_SP('Honduras');
    FIDE_PAIS_TB_INSERTAR_SP('Guatemala');
    FIDE_PAIS_TB_INSERTAR_SP('México');
    FIDE_PAIS_TB_INSERTAR_SP('Colombia');
    FIDE_PAIS_TB_INSERTAR_SP('Ecuador');
    FIDE_PAIS_TB_INSERTAR_SP('Perú');
    FIDE_PAIS_TB_INSERTAR_SP('Venezuela');
    FIDE_PAIS_TB_INSERTAR_SP('Brasil');
    FIDE_PAIS_TB_INSERTAR_SP('Argentina');
    FIDE_PAIS_TB_INSERTAR_SP('Chile');
    FIDE_PAIS_TB_INSERTAR_SP('Uruguay');
END;
/

-- Inserciones para la tabla FIDE_PROVINCIA_TB
BEGIN
    FIDE_PROVINCIA_TB_INSERTAR_SP('San José');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Alajuela');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Cartago');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Heredia');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Guanacaste');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Puntarenas');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Limón');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Panamá Oeste');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Colón');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Chiriquí');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Veraguas');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Coclé');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Los Santos');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Darién');
    FIDE_PROVINCIA_TB_INSERTAR_SP('Bocas del Toro');
END;
/

-- Inserciones para la tabla FIDE_CANTON_TB
BEGIN
    FIDE_CANTON_TB_INSERTAR_SP('Central');
    FIDE_CANTON_TB_INSERTAR_SP('Escazú');
    FIDE_CANTON_TB_INSERTAR_SP('Desamparados');
    FIDE_CANTON_TB_INSERTAR_SP('Puriscal');
    FIDE_CANTON_TB_INSERTAR_SP('Tarrazú');
    FIDE_CANTON_TB_INSERTAR_SP('Aserrí');
    FIDE_CANTON_TB_INSERTAR_SP('Mora');
    FIDE_CANTON_TB_INSERTAR_SP('Goicoechea');
    FIDE_CANTON_TB_INSERTAR_SP('Santa Ana');
    FIDE_CANTON_TB_INSERTAR_SP('Alajuelita');
    FIDE_CANTON_TB_INSERTAR_SP('Vásquez de Coronado');
    FIDE_CANTON_TB_INSERTAR_SP('Acosta');
    FIDE_CANTON_TB_INSERTAR_SP('Tibás');
    FIDE_CANTON_TB_INSERTAR_SP('Moravia');
    FIDE_CANTON_TB_INSERTAR_SP('Montes de Oca');
END;
/

-- Inserciones para la tabla FIDE_DISTRITO_TB
BEGIN
    FIDE_DISTRITO_TB_INSERTAR_SP('Carmen');
    FIDE_DISTRITO_TB_INSERTAR_SP('Merced');
    FIDE_DISTRITO_TB_INSERTAR_SP('Hospital');
    FIDE_DISTRITO_TB_INSERTAR_SP('Zapote');
    FIDE_DISTRITO_TB_INSERTAR_SP('San Francisco de Dos Ríos');
    FIDE_DISTRITO_TB_INSERTAR_SP('Uruca');
    FIDE_DISTRITO_TB_INSERTAR_SP('Mata Redonda');
    FIDE_DISTRITO_TB_INSERTAR_SP('Pavas');
    FIDE_DISTRITO_TB_INSERTAR_SP('Hatillo');
    FIDE_DISTRITO_TB_INSERTAR_SP('San Sebastián');
    FIDE_DISTRITO_TB_INSERTAR_SP('Escazú Centro');
    FIDE_DISTRITO_TB_INSERTAR_SP('San Rafael de Escazú');
    FIDE_DISTRITO_TB_INSERTAR_SP('San Antonio de Escazú');
    FIDE_DISTRITO_TB_INSERTAR_SP('Gravilias');
    FIDE_DISTRITO_TB_INSERTAR_SP('San Felipe');
END;
/

-- Inserciones para la tabla FIDE_CLIENTES_TB
BEGIN
    FIDE_CLIENTES_TB_INSERTAR_SP('Juan', '61412345', 123456789, 'juan.perez@gmail.com', 1, 1, 1, 1, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('María', '61498765', 987654321, 'maria.rodriguez@hotmail.com', 1, 2, 1, 2, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Carlos', '61122334', 112233445, 'carlos.martinez@yahoo.com', 2, 3, 2, 3, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Ana', '61033445', 223344556, 'ana.gonzalez@gmail.com', 2, 4, 2, 4, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Luis', '61987654', 334455667, 'luis.fernandez@outlook.com', 3, 5, 3, 5, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Sofía', '61876543', 445566778, 'sofia.diaz@gmail.com', 3, 6, 3, 6, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Ricardo', '61765432', 556677889, 'ricardo.lopez@hotmail.com', 4, 7, 4, 7, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Laura', '61654321', 667788990, 'laura.torres@yahoo.com', 4, 8, 4, 8, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('José', '61543210', 778899001, 'jose.perez@gmail.com', 5, 9, 5, 9, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Isabel', '61332109', 889900112, 'isabel.sanchez@gmail.com', 5, 10, 5, 10, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Diego', '61221098', 990011223, 'diego.rivera@outlook.com', 6, 11, 6, 11, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Patricia', '61110987', 101112233, 'patricia.ramirez@gmail.com', 6, 12, 6, 12, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Andrés', '61019876', 112233344, 'andres.jimenez@yahoo.com', 7, 13, 7, 13, NULL, 1);
    FIDE_CLIENTES_TB_INSERTAR_SP('Carmen', '61908765', 223344455, 'carmen.morales@hotmail.com', 7, 14, 7, 14, NULL, 1);
END;
/

-- Inserciones para la tabla FIDE_PROVEEDORES_TB
BEGIN
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor A', 'Proveedor de productos electrónicos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor B', 'Proveedor de ropa', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor C', 'Proveedor de artículos de hogar', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor D', 'Proveedor de alimentos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor E', 'Proveedor de artículos deportivos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor F', 'Proveedor de tecnología', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor G', 'Proveedor de artículos de oficina', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor H', 'Proveedor de productos de belleza', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor I', 'Proveedor de artículos de jardín', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor J', 'Proveedor de juguetes', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor K', 'Proveedor de repuestos para autos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor L', 'Proveedor de productos ecológicos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor M', 'Proveedor de alimentos orgánicos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor N', 'Proveedor de equipos médicos', 1);
    FIDE_PROVEEDORES_TB_INSERTAR_SP('Proveedor O', 'Proveedor de libros', 1);
END;
/

-- Inserciones para la tabla FIDE_INVENTARIO_TB
BEGIN
    FIDE_INVENTARIO_TB_INSERTAR_SP('Laptop Dell', NULL, 500, 'Laptop con procesador Intel i7', 10, 'Electrónica', 1, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Camiseta Nike', NULL, 30, 'Camiseta deportiva de algodón', 100, 'Ropa', 2, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Silla ergonómica', NULL, 120, 'Silla cómoda para oficina', 15, 'Mobiliario', 3, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Pizza de pepperoni', NULL, 8, 'Pizza grande con pepperoni', 50, 'Alimentos', 4, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Balón de fútbol', NULL, 25, 'Balón de fútbol tamaño 5', 80, 'Deportes', 5, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Smartphone Samsung', NULL, 300, 'Teléfono inteligente Samsung Galaxy', 50, 'Electrónica', 6, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Lámpara LED', NULL, 40, 'Lámpara de escritorio con luz LED', 20, 'Iluminación', 7, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Crema antiarrugas', NULL, 15, 'Crema de noche antiarrugas', 200, 'Belleza', 8, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Regadera', NULL, 10, 'Regadera de jardín con presión ajustable', 30, 'Hogar', 9, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Pelota de playa', NULL, 12, 'Pelota inflable de playa', 100, 'Deportes', 10, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Camión de juguetes', NULL, 18, 'Camión de juguete para niños', 150, 'Juguetes', 11, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Aceite de motor', NULL, 20, 'Aceite sintético para autos', 40, 'Automotriz', 12, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Libro de recetas', NULL, 25, 'Libro con recetas de cocina internacional', 200, 'Libros', 13, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Cesta de frutas', NULL, 5, 'Cesta con variedad de frutas frescas', 100, 'Alimentos', 14, 1);
    FIDE_INVENTARIO_TB_INSERTAR_SP('Máquina de café', NULL, 150, 'Máquina de café espresso', 30, 'Electrodomésticos', 15, 1);
END;
/

-- Inserciones para la tabla FIDE_FEEDBACK_TB
BEGIN
    FIDE_FEEDBACK_TB_INSERTAR_SP(1, 1, 'Excelente servicio y productos de calidad.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(2, 1, 'Muy buena atención al cliente.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(3, 1, 'La entrega fue puntual, todo perfecto.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(4, 1, 'Recomiendo este sitio, buena variedad.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(5, 2, 'El producto llegó dañado, espero que me ayuden.', 2);
    FIDE_FEEDBACK_TB_INSERTAR_SP(6, 1, 'Muy fácil de navegar, excelente experiencia de compra.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(7, 1, 'La calidad de los productos es insuperable.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(8, 2, 'Algunas opciones de pago son limitadas.', 2);
    FIDE_FEEDBACK_TB_INSERTAR_SP(9, 1, 'Me encantaron los precios, volveré a comprar.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(10, 2, 'Tuve problemas con la entrega, pero la atención fue buena.', 2);
    FIDE_FEEDBACK_TB_INSERTAR_SP(11, 1, 'La compra fue rápida y todo llegó bien.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(12, 1, 'Todo perfecto, como esperaba.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(13, 1, 'Gran variedad de productos, siempre encuentro lo que busco.', 1);
    FIDE_FEEDBACK_TB_INSERTAR_SP(14, 1, 'El proceso de devolución fue sencillo, muy agradecido.', 1);
END;

/

-- Inserciones para la tabla FIDE_CARRITO_TB
BEGIN
    FIDE_CARRITO_TB_INSERTAR_SP(1, 2, 1000, 1, 1);
    FIDE_CARRITO_TB_INSERTAR_SP(2, 1, 30, 1, 2);
    FIDE_CARRITO_TB_INSERTAR_SP(3, 3, 240, 1, 3);
    FIDE_CARRITO_TB_INSERTAR_SP(4, 4, 120, 1, 4);
    FIDE_CARRITO_TB_INSERTAR_SP(5, 5, 50, 1, 5);
    FIDE_CARRITO_TB_INSERTAR_SP(6, 6, 300, 1, 6);
    FIDE_CARRITO_TB_INSERTAR_SP(7, 7, 40, 1, 7);
    FIDE_CARRITO_TB_INSERTAR_SP(8, 8, 30, 1, 8);
    FIDE_CARRITO_TB_INSERTAR_SP(9, 9, 25, 1, 9);
    FIDE_CARRITO_TB_INSERTAR_SP(10, 10, 18, 1, 10);
    FIDE_CARRITO_TB_INSERTAR_SP(11, 11, 40, 1, 11);
    FIDE_CARRITO_TB_INSERTAR_SP(12, 12, 80, 1, 12);
    FIDE_CARRITO_TB_INSERTAR_SP(13, 13, 35, 1, 13);
    FIDE_CARRITO_TB_INSERTAR_SP(14, 14, 10, 1, 14);
END;
/

-- Inserciones para la tabla FIDE_CARRITO_TEMP_TB
BEGIN
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(1, 2, 1000, 1, 1);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(2, 1, 30, 1, 2);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(3, 3, 240, 1, 3);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(4, 4, 120, 1, 4);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(5, 5, 50, 1, 5);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(6, 6, 300, 1, 6);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(7, 7, 40, 1, 7);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(8, 8, 30, 1, 8);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(9, 9, 25, 1, 9);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(10, 10, 18, 1, 10);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(11, 11, 40, 1, 11);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(12, 12, 80, 1, 12);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(13, 13, 35, 1, 13);
    FIDE_CARRITO_TEMP_TB_INSERTAR_SP(14, 14, 10, 1, 14);
END;
/


BEGIN
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Tarjeta de Crédito', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Transferencia Bancaria', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Efectivo', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Paypal', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Tarjeta Débito', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Bitcoin', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Google Pay', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Apple Pay', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Stripe', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Pago Contra Entrega', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Pago en Tienda', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Transferencia a Cuenta', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Pago por QR', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('Kioscos de Pagos', 1);
    FIDE_METODO_PAGO_TB_INSERTAR_SP('PSE', 1);
END;
/
SELECT * FROM FIDE_FACTURA_TB;
BEGIN
    FIDE_FACTURA_TB_INSERTAR_SP(1, 1, 'Compra de Ropa', 3, 12000, 10000, 2000, 500, 1, 101);
    FIDE_FACTURA_TB_INSERTAR_SP(2, 2, 'Compra de Accesorios', 2, 8000, 7000, 1400, 600, 2, 102);
    FIDE_FACTURA_TB_INSERTAR_SP(3, 1, 'Compra de Zapatos', 1, 5000, 4500, 900, 400, 1, 103);
    FIDE_FACTURA_TB_INSERTAR_SP(4, 3, 'Compra de Perfumes', 4, 15000, 12000, 3000, 700, 2, 104);
    FIDE_FACTURA_TB_INSERTAR_SP(5, 4, 'Compra de Bolsos', 2, 10000, 9000, 1800, 450, 1, 105);
    FIDE_FACTURA_TB_INSERTAR_SP(6, 2, 'Compra de Camisetas', 3, 6000, 5000, 1000, 300, 1, 106);
    FIDE_FACTURA_TB_INSERTAR_SP(7, 1, 'Compra de Juguetes', 1, 4000, 3500, 700, 350, 2, 107);
    FIDE_FACTURA_TB_INSERTAR_SP(8, 5, 'Compra de Sillas', 4, 20000, 18000, 3600, 800, 2, 108);
    FIDE_FACTURA_TB_INSERTAR_SP(9, 6, 'Compra de Muebles', 2, 11000, 10000, 2000, 500, 1, 109);
    FIDE_FACTURA_TB_INSERTAR_SP(10, 7, 'Compra de Artículos de Cocina', 3, 7000, 6000, 1200, 350, 1, 110);
    FIDE_FACTURA_TB_INSERTAR_SP(11, 3, 'Compra de Teléfonos', 1, 15000, 12000, 2400, 600, 2, 111);
    FIDE_FACTURA_TB_INSERTAR_SP(12, 4, 'Compra de Electrónica', 4, 18000, 15000, 3000, 700, 2, 112);
    FIDE_FACTURA_TB_INSERTAR_SP(13, 5, 'Compra de Tecnología', 3, 20000, 18000, 3600, 750, 1, 113);
    FIDE_FACTURA_TB_INSERTAR_SP(14, 6, 'Compra de Relojes', 2, 9000, 8000, 1600, 450, 1, 114);
END;
/

BEGIN
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Correos de Costa Rica', 5000, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('DHL', 8000, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('FedEx', 7500, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('UPS', 7200, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Estafeta', 6000, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Tigo', 5500, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Cargill', 6400, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('RedPack', 5000, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Azul Cargo', 6800, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('TMS', 5300, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('JetBox', 6100, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Blue Parcel', 5600, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('MRW', 5000, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Kiala', 4900, 1);
    FIDE_EMPRESA_ENVIOS_TB_INSERTAR_SP('Interlink', 6700, 1);
END;
/

BEGIN
    FIDE_ENVIOS_TB_INSERTAR_SP(1, 2, 1, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(2, 3, 2, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(3, 4, 1, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(4, 5, 3, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(5, 6, 2, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(6, 7, 1, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(7, 8, 3, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(8, 9, 2, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(9, 10, 1, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(10, 11, 3, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(11, 12, 2, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(12, 13, 1, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(13, 14, 3, 1);
    FIDE_ENVIOS_TB_INSERTAR_SP(14, 15, 2, 1);
END;
/
